### ISSUE TITLE
need sql fix

### ISSUE THREAD

**Issue by JaeHyun-Lim-dev** [1wooo/kb_miniproject#8]
https://github.com/1wooo/kb_miniproject/blob/a473fedd1546b9a8cf86810421941e4490501195/resources/scheam/projectSchema.sql#L22

need change to
```
ALTER TABLE BOARDDTO ADD CONSTRAINT fk_reply_no foreign KEY(selected_reply) references REPLY (selected_reply) ON DELETE SET NULL;
```
(ON DELETE CASCADE 설정 시 댓글을 삭제하면 글이 삭제되지 않나요?)

**Comment by seojisoosoo** [comment]
오라클 developer에서 확인해보았는데, 
`delete from reply where reply_no=25; `
이런식으로 where조건 걸고 삭제했을 때 글 남아있습니다!

**Comment by JaeHyun-Lim-dev** [comment]
앗 그럼 이슈 닫을게요 굿굿
